---
- hosts: all
  become: yes
  order: sorted

  tasks:
    - name: Read current hostname
      command:
        cmd: "cat /etc/hostname"
      register: old_hostname
      changed_when: false

    - name: Work to change hostname if it was NoName
      import_tasks: "UpdateNoNameHostnames.yml"
      when: (old_hostname.stdout) is match('NoName')

    - name: Upgrade apt installation if needed
      apt:
        upgrade: 'yes'
        update_cache: 'yes'
        cache_valid_time: 3600  # Don't run more than once an hour
        state: latest

    - name: See if reboot is now needed
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Skip reboot unless reboot-required file is present
      # Use shell so we can sleep-a-bit while ansible wraps up
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0
      when: reboot_required_file.stat.exists

    - name: Wait for the reboot to complete if there was a change.
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
      when: reboot_required_file.stat.exists
...
