---
- hosts: all
  become: yes
  order: sorted

  tasks:
    - name: Fix file to use https
      command:
        cmd: sed -i 's/http:/https:/g' /etc/apt/sources.list

    - name: Fix upgrade to oracular (when Update.yml failed)
      command:
        cmd: sed -i 's/oracular/noble/g' /etc/apt/sources.list
...
