# This is modeled after ./inventory/sample/hosts.ini

# First group of hosts are 7 true Raspberry Pi 4, stacked on
# plexiglass separataros, with IP address *.100, ... *.106

[master]
# List of hosts that should form the control plane.
# I had 3 hosts, but 1 is sufficient.
10.1.8.[100:102]

[node]
# List of hosts that are worker nodes.
10.1.8.[103:106]

[k3s_cluster:children]
master
node

#-------------------------------------
# That is the end of the requisite groups for running site.yml, and reset.yml
#-------------------------------------


# The 3 hosts in "master" don't seem to establesh a high
# availability control plane, so I need to install
# grafana and prometheus in the sole (lead) control
# node.
[lead]
10.1.8.100

[super]
# Running on Compute Modules in SuperC6
10.1.8.110  #cm1  16GB EMMC; Wifi
10.1.8.111  #cm2  16GB EMMC; Wifi
10.1.8.112  #cm3  16GB EMMC;
10.1.8.113  #cm4  16GB EMMC;
10.1.8.114  #cm5  16GB EMMC;
10.1.8.115  #cm6  16GB EMMC;

[pi5]
# Raspberry PI 5  (which both have 2.5GB ethernet)
10.1.8.107 # Individual red/white case with fan
# Raspberry PI Compute module 5 in IO board case
10.1.8.108 # Individual black case with no fan, 16GB, WiFi

[all:children]
# For convenience in running ansible commands, I define "all"
k3s_cluster
pi5
super

[sample]
# For convenience in running ansible experiments, I define
10.1.8.100
