---
- name: Enable cgroup via boot commandline if not already enabled for Ubuntu on a Raspberry Pi
  lineinfile:
    path: /boot/firmware/cmdline.txt
    backrefs: yes
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
  register: cmdline_text

- name: Reboot immediately if we edited the cmdline.txt file
  # Better would be to also check /proc/cgroups for the desired lines,
  # and only then reboot if we had to.
  # Note that we can't complete the install if /proc/cgroups doesn't have
  # "memory" (and probably "cpuset") lines which end in '1' (which means "enabled").
  reboot:
  when: cmdline_text.changed

